# Auto-generated by Invoke-AttackLifecycle.ps1 - attacker=170.187.158.212
$Global:EalDemo.DomainController = 'DC01.corp.local'
$Global:EalDemo.Domain = 'corp.local'
$Global:EalDemo.AttackerC2 = '170.187.158.212'
