<#
    Start-Demo.ps1  --  Generic guided launcher (shared by cases 2-5).
    ================================================================
    Double-click Start-Demo.cmd (self-elevates + sets execution policy) or run
    this directly. It reads the case's Run-All.ps1 and config, and offers a
    menu so you never have to remember commands. Config fields (if any) come
    from $cfg._ConfigFields defined in that case's config\lab-config.ps1.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\config\lab-config.ps1"
$cfg      = $Global:EalDemo
$scripts  = Join-Path $PSScriptRoot 'scripts'
$localCfg = Join-Path $PSScriptRoot 'config\lab-config.local.ps1'
$fields   = @(); if ($cfg.ContainsKey('_ConfigFields')) { $fields = $cfg._ConfigFields }
$stageNums = @($cfg._StageMap.Keys | Sort-Object)
$stageLo   = $stageNums[0]; $stageHi = $stageNums[-1]

function Pause-Return { Write-Host ""; Read-Host "Press Enter to return to the menu" | Out-Null }

function Write-LocalConfig {
    $lines = @('# Auto-generated by Start-Demo.ps1 - edit via the menu, not by hand.')
    foreach ($f in $fields) {
        $esc = ("" + $cfg[$f.Key]) -replace "'", "''"
        $lines += "`$Global:EalDemo.$($f.Key) = '$esc'"
    }
    Set-Content -Path $localCfg -Value $lines -Encoding UTF8
}

function Save-Config {
    if (-not $fields) { Write-Stage "This case needs no configuration - just run it." "OK"; Pause-Return; return }
    Write-Host "`n-- Configure (Enter keeps the current value) --`n" -ForegroundColor Cyan
    foreach ($f in $fields) {
        $ans = Read-Host "$($f.Prompt) [$($cfg[$f.Key])]"
        if (-not [string]::IsNullOrWhiteSpace($ans)) { $cfg[$f.Key] = $ans }
    }
    Write-LocalConfig
    Write-Stage "Saved to config\lab-config.local.ps1" "OK"
    Pause-Return
}

function Invoke-Chain {
    param([int[]]$Stages, [switch]$DryRun, [switch]$PauseBetween)
    $a = @{ Stages = $Stages }
    if ($DryRun)       { $a.DryRun = $true }
    if ($PauseBetween) { $a.PauseBetween = $true }
    & (Join-Path $scripts 'Run-All.ps1') @a
    Pause-Return
}

function Show-Expected {
    Get-Content (Join-Path $PSScriptRoot 'README.md') |
        Select-String -Pattern '^\| \d ' | ForEach-Object { Write-Host $_.Line -ForegroundColor Gray }
    Write-Host "`n(Full detail in README.md / docs\verification-checklist.md)" -ForegroundColor DarkGray
    Pause-Return
}

function Show-Menu {
    Clear-Host
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host "   $($cfg._Title)" -ForegroundColor Magenta
    Write-Host "   Attacker host: $($cfg.AttackerHostname)" -ForegroundColor DarkGray
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "  [2] Preflight  - check reachability" -ForegroundColor Green
    Write-Host "  [3] Dry run    - print the whole chain, send NO traffic"
    Write-Host "  [4] RUN full attack chain (pause between stages)" -ForegroundColor Green
    Write-Host "  [5] Run a single stage..."
    Write-Host "  [6] Show expected alerts"
    if ($fields) { Write-Host "  [1] Configure targets (no file editing)" }
    Write-Host "  [Q] Quit"
    Write-Host ""
}

if ($fields -and -not (Test-Path $localCfg)) {
    Write-Host "`nThis case has targets to set." -ForegroundColor Yellow
    if ((Read-Host "Configure them now? [Y/n]").Trim().ToUpper() -ne 'N') { Save-Config }
}

do {
    Show-Menu
    switch ((Read-Host "Choose").Trim().ToUpper()) {
        '1' { Save-Config }
        '2' { & (Join-Path $scripts '00-preflight.ps1'); Pause-Return }
        '3' { Invoke-Chain -Stages $stageNums -DryRun }
        '4' { Invoke-Chain -Stages $stageNums -PauseBetween }
        '5' {
                $s = Read-Host "Stage number ($stageLo-$stageHi)"
                if (($s -match '^\d+$') -and ($stageNums -contains [int]$s)) { Invoke-Chain -Stages @([int]$s) -PauseBetween }
                else { Write-Stage "Not a valid stage." "WARN"; Pause-Return }
             }
        '6' { Show-Expected }
        'Q' { break }
        default { }
    }
} while ($true)

Write-Host "`nBye. Open Cortex XSIAM/XDR to review the alerts.`n" -ForegroundColor Green
