# Auto-generated by Invoke-AttackLifecycle.ps1 - attacker=170.187.158.212
$Global:EalDemo.IcmpTarget = '170.187.158.212'
$Global:EalDemo.SshServers = '170.187.158.212:2201,170.187.158.212:2202,170.187.158.212:2203'
$Global:EalDemo.FtpServer = '170.187.158.212'
$Global:EalDemo.AttackerC2 = '170.187.158.212'
$Global:EalDemo.SmbShare = '\\170.187.158.212\share'
