<#
    Start-Demo.ps1  --  One-stop launcher for the EAL demo.
    ======================================================
    Double-click Start-Demo.cmd (it self-elevates and sets the execution
    policy), or run this directly:  .\Start-Demo.ps1

    Gives you a menu so you never have to remember commands or open the
    config file: configure the lab, preflight, dry-run, or fire the chain.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\config\lab-config.ps1"
$cfg        = $Global:EalDemo
$scripts    = Join-Path $PSScriptRoot 'scripts'
$localCfg   = Join-Path $PSScriptRoot 'config\lab-config.local.ps1'

# Values persisted to the local-override file (auto-detect + manual both use this)
$script:PersistKeys = @('Domain','DomainController','DCIpAddress',
                        'LateralTarget','LateralTargetIp','LabUser',
                        'DgaRootDomain','ExfilUrl')

function Pause-Return { Write-Host ""; Read-Host "Press Enter to return to the menu" | Out-Null }

function Write-LocalConfig {
    $lines = @('# Auto-generated by Start-Demo.ps1 - edit via the menu, not by hand.')
    foreach ($k in $script:PersistKeys) {
        $esc = ("" + $cfg[$k]) -replace "'", "''"
        $lines += "`$Global:EalDemo.$k = '$esc'"
    }
    Set-Content -Path $localCfg -Value $lines -Encoding UTF8
}

function Invoke-AutoDetect {
    <# Populate $cfg from THIS machine's domain membership, then persist it.
       Fills domain, DC + IP, current user, and best-effort lateral target.
       Leaves the external C2/exfil domains as defaults - it can't know those. #>
    Write-Host "`n-- Auto-detecting lab settings from this machine --`n" -ForegroundColor Cyan

    # Current user (attacker identity)
    $cfg.LabUser = "$env:USERDOMAIN\$env:USERNAME"
    Write-Stage "User          : $($cfg.LabUser)" "OK"

    # Domain FQDN
    $domain = $env:USERDNSDOMAIN
    if (-not $domain) {
        try { $domain = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name } catch {}
    }
    if ($domain) {
        $cfg.Domain = $domain.ToLower()
        Write-Stage "Domain        : $($cfg.Domain)" "OK"
    } else {
        Write-Stage "Not domain-joined - keeping default domain. Stages 2-4 need AD; stages 1 & 5 still work." "WARN"
    }

    # Domain Controller + its IP
    $dcFqdn = $null; $dcIp = $null
    try {
        $dc     = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().FindDomainController()
        $dcFqdn = $dc.Name; $dcIp = $dc.IPAddress
    } catch {
        $ls = ($env:LOGONSERVER -replace '^\\\\', '')
        if ($ls -and $domain) { $dcFqdn = "$ls.$domain" }
    }
    if ($dcFqdn) {
        $cfg.DomainController = $dcFqdn
        if (-not $dcIp) {
            try { $dcIp = (Resolve-DnsName $dcFqdn -Type A -QuickTimeout -ErrorAction Stop |
                           Where-Object IPAddress | Select-Object -First 1 -Expand IPAddress) } catch {}
        }
        if ($dcIp) { $cfg.DCIpAddress = $dcIp }
        Write-Stage "Domain Ctrlr  : $($cfg.DomainController) ($($cfg.DCIpAddress))" "OK"
    } else {
        Write-Stage "Could not locate a DC automatically - set it via [1] if stages 2-4 are needed." "WARN"
    }

    # Lateral target: first non-DC domain computer that answers on RPC/135.
    if ($domain -and $dcFqdn) {
        Write-Stage "Searching for a member server to use as the lateral target..." "INFO"
        try {
            $entry = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($cfg.DomainController)")
            $ds    = New-Object System.DirectoryServices.DirectorySearcher($entry,
                        "(&(objectCategory=computer)(!(userAccountControl:1.2.840.113556.1.4.803:=8192)))")
            $ds.PageSize = 100; $ds.SizeLimit = 50
            $ds.PropertiesToLoad.Add("dnshostname") | Out-Null
            $picked = $null; $tested = 0
            foreach ($r in $ds.FindAll()) {
                $h = $r.Properties["dnshostname"]
                if (-not $h) { continue }
                $dnsHost = [string]$h[0]
                if (-not $dnsHost -or $dnsHost -eq $cfg.DomainController) { continue }
                if ($tested -ge 15) { break }   # don't scan huge domains forever
                $tested++
                if (Test-NetConnection -ComputerName $dnsHost -Port 135 -InformationLevel Quiet -WarningAction SilentlyContinue) {
                    $picked = $dnsHost; break
                }
            }
            if ($picked) {
                $cfg.LateralTarget = $picked
                try { $ip = (Resolve-DnsName $picked -Type A -QuickTimeout -ErrorAction Stop |
                             Where-Object IPAddress | Select-Object -First 1 -Expand IPAddress)
                      if ($ip) { $cfg.LateralTargetIp = $ip } } catch {}
                Write-Stage "Lateral target: $($cfg.LateralTarget) ($($cfg.LateralTargetIp))  <- confirm you are ADMIN here" "OK"
            } else {
                Write-Stage "No reachable member server found - stage 4 needs a host where you're admin; set it via [1]." "WARN"
            }
        } catch {
            Write-Stage "Lateral-target discovery skipped: $($_.Exception.Message)" "WARN"
        }
    }

    Write-Stage "C2 root domain + Exfil URL are EXTERNAL - can't be detected; using defaults." "INFO"
    Write-Stage "  DgaRootDomain = $($cfg.DgaRootDomain)" "INFO"
    Write-Stage "  ExfilUrl      = $($cfg.ExfilUrl)" "INFO"
    Write-Stage "  (Set your own via [1] if you control a domain/endpoint - otherwise these still generate loggable traffic.)" "INFO"

    Write-LocalConfig
    Write-Stage "Saved detected settings to config\lab-config.local.ps1" "OK"
}

function Test-Admin {
    ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Save-Config {
    <# Interactively collect the few lab values and persist them to the
       local-override file so the stage scripts pick them up automatically. #>
    Write-Host "`n-- Configure lab (press Enter to keep the current value) --`n" -ForegroundColor Cyan
    $fields = @(
        @{ Key='Domain';           Prompt='AD domain (FQDN)' }
        @{ Key='DomainController'; Prompt='Domain Controller host' }
        @{ Key='DCIpAddress';      Prompt='DC IP address' }
        @{ Key='LateralTarget';    Prompt='Lateral-movement target host' }
        @{ Key='LateralTargetIp';  Prompt='Lateral target IP address' }
        @{ Key='LabUser';          Prompt='Lab user (domain\user)' }
        @{ Key='DgaRootDomain';    Prompt='C2/DGA root domain' }
        @{ Key='ExfilUrl';         Prompt='Exfil upload URL' }
    )
    foreach ($f in $fields) {
        $cur = $cfg[$f.Key]
        $ans = Read-Host "$($f.Prompt) [$cur]"
        if (-not [string]::IsNullOrWhiteSpace($ans)) { $cfg[$f.Key] = $ans }
    }
    Write-LocalConfig
    Write-Stage "Saved settings to config\lab-config.local.ps1" "OK"
    Pause-Return
}

function Invoke-Chain {
    param([int[]]$Stages, [switch]$DryRun, [switch]$PauseBetween)
    $args = @{ Stages = $Stages }
    if ($DryRun)       { $args.DryRun = $true }
    if ($PauseBetween) { $args.PauseBetween = $true }
    & (Join-Path $scripts 'Run-All.ps1') @args
    Pause-Return
}

function Show-Menu {
    Clear-Host
    $adm = if (Test-Admin) { 'elevated' } else { 'NOT elevated (stage 4 needs admin)' }
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host "   PANW EAL Demo - Case 1 : guided launcher" -ForegroundColor Magenta
    Write-Host "   Domain: $($cfg.Domain)   DC: $($cfg.DomainController)"    -ForegroundColor DarkGray
    Write-Host "   Target: $($cfg.LateralTarget)   Session: $adm"           -ForegroundColor DarkGray
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "  [A] Auto-detect settings from THIS machine (recommended)" -ForegroundColor Green
    Write-Host "  [1] Configure lab settings manually (no file editing)"
    Write-Host "  [2] Preflight - check connectivity"
    Write-Host "  [3] Dry run  - print the whole chain, send NO traffic"
    Write-Host "  [4] RUN full attack chain (pause between stages)"
    Write-Host "  [5] Run C2 + Exfil only  (stages 1 & 5, no AD lab needed)"
    Write-Host "  [6] Run a single stage..."
    Write-Host "  [7] Show expected Cortex alerts (README section 6)"
    Write-Host "  [Q] Quit"
    Write-Host ""
}

function Show-Expected {
    $readme = Join-Path $PSScriptRoot 'README.md'
    Write-Host ""
    Get-Content $readme | Select-String -Pattern '^\| \d ' -Context 0 |
        ForEach-Object { Write-Host $_.Line -ForegroundColor Gray }
    Write-Host "`n(Full detail in README.md section 6 / docs\verification-checklist.md)" -ForegroundColor DarkGray
    Pause-Return
}

# First run (no saved settings yet): offer to auto-detect straight away.
if (-not (Test-Path $localCfg)) {
    Write-Host "`nNo saved settings found for this machine." -ForegroundColor Yellow
    if ((Read-Host "Auto-detect domain/DC/target from this machine now? [Y/n]").Trim().ToUpper() -ne 'N') {
        Invoke-AutoDetect; Pause-Return
    }
}

do {
    Show-Menu
    switch ((Read-Host "Choose").Trim().ToUpper()) {
        'A' { Invoke-AutoDetect; Pause-Return }
        '1' { Save-Config }
        '2' { & (Join-Path $scripts '00-preflight.ps1'); Pause-Return }
        '3' { Invoke-Chain -Stages @(1,2,3,4,5) -DryRun }
        '4' {
                if (-not (Test-Admin)) { Write-Stage "Heads-up: not elevated, stage 4 may fail." "WARN" }
                Invoke-Chain -Stages @(1,2,3,4,5) -PauseBetween
             }
        '5' { Invoke-Chain -Stages @(1,5) -PauseBetween }
        '6' {
                $s = Read-Host "Stage number (1-5)"
                if ($s -match '^[1-5]$') { Invoke-Chain -Stages @([int]$s) -PauseBetween }
                else { Write-Stage "Not a valid stage." "WARN"; Pause-Return }
             }
        '7' { Show-Expected }
        'Q' { break }
        default { }
    }
} while ($true)

Write-Host "`nBye. Open Cortex XSIAM/XDR to review the alerts.`n" -ForegroundColor Green
