<#
    Start-Demo.ps1  --  One-stop launcher for the EAL demo.
    ======================================================
    Double-click Start-Demo.cmd (it self-elevates and sets the execution
    policy), or run this directly:  .\Start-Demo.ps1

    Gives you a menu so you never have to remember commands or open the
    config file: configure the lab, preflight, dry-run, or fire the chain.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\config\lab-config.ps1"
$cfg        = $Global:EalDemo
$scripts    = Join-Path $PSScriptRoot 'scripts'
$localCfg   = Join-Path $PSScriptRoot 'config\lab-config.local.ps1'

function Pause-Return { Write-Host ""; Read-Host "Press Enter to return to the menu" | Out-Null }

function Test-Admin {
    ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Save-Config {
    <# Interactively collect the few lab values and persist them to the
       local-override file so the stage scripts pick them up automatically. #>
    Write-Host "`n-- Configure lab (press Enter to keep the current value) --`n" -ForegroundColor Cyan
    $fields = @(
        @{ Key='Domain';           Prompt='AD domain (FQDN)' }
        @{ Key='DomainController'; Prompt='Domain Controller host' }
        @{ Key='DCIpAddress';      Prompt='DC IP address' }
        @{ Key='LateralTarget';    Prompt='Lateral-movement target host' }
        @{ Key='LateralTargetIp';  Prompt='Lateral target IP address' }
        @{ Key='LabUser';          Prompt='Lab user (domain\user)' }
        @{ Key='DgaRootDomain';    Prompt='C2/DGA root domain' }
        @{ Key='ExfilUrl';         Prompt='Exfil upload URL' }
    )
    $lines = @('# Auto-generated by Start-Demo.ps1 - edit via the menu, not by hand.')
    foreach ($f in $fields) {
        $cur = $cfg[$f.Key]
        $ans = Read-Host "$($f.Prompt) [$cur]"
        $val = if ([string]::IsNullOrWhiteSpace($ans)) { $cur } else { $ans }
        $cfg[$f.Key] = $val
        $esc = $val -replace "'", "''"
        $lines += "`$Global:EalDemo.$($f.Key) = '$esc'"
    }
    Set-Content -Path $localCfg -Value $lines -Encoding UTF8
    Write-Stage "Saved settings to config\lab-config.local.ps1" "OK"
    Pause-Return
}

function Invoke-Chain {
    param([int[]]$Stages, [switch]$DryRun, [switch]$PauseBetween)
    $args = @{ Stages = $Stages }
    if ($DryRun)       { $args.DryRun = $true }
    if ($PauseBetween) { $args.PauseBetween = $true }
    & (Join-Path $scripts 'Run-All.ps1') @args
    Pause-Return
}

function Show-Menu {
    Clear-Host
    $adm = if (Test-Admin) { 'elevated' } else { 'NOT elevated (stage 4 needs admin)' }
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host "   PANW EAL Demo - Case 1 : guided launcher" -ForegroundColor Magenta
    Write-Host "   Domain: $($cfg.Domain)   DC: $($cfg.DomainController)"    -ForegroundColor DarkGray
    Write-Host "   Target: $($cfg.LateralTarget)   Session: $adm"           -ForegroundColor DarkGray
    Write-Host "============================================================" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "  [1] Configure lab settings (no file editing)"
    Write-Host "  [2] Preflight - check connectivity"
    Write-Host "  [3] Dry run  - print the whole chain, send NO traffic"
    Write-Host "  [4] RUN full attack chain (pause between stages)"
    Write-Host "  [5] Run C2 + Exfil only  (stages 1 & 5, no AD lab needed)"
    Write-Host "  [6] Run a single stage..."
    Write-Host "  [7] Show expected Cortex alerts (README section 6)"
    Write-Host "  [Q] Quit"
    Write-Host ""
}

function Show-Expected {
    $readme = Join-Path $PSScriptRoot 'README.md'
    Write-Host ""
    Get-Content $readme | Select-String -Pattern '^\| \d ' -Context 0 |
        ForEach-Object { Write-Host $_.Line -ForegroundColor Gray }
    Write-Host "`n(Full detail in README.md section 6 / docs\verification-checklist.md)" -ForegroundColor DarkGray
    Pause-Return
}

do {
    Show-Menu
    switch ((Read-Host "Choose").Trim().ToUpper()) {
        '1' { Save-Config }
        '2' { & (Join-Path $scripts '00-preflight.ps1'); Pause-Return }
        '3' { Invoke-Chain -Stages @(1,2,3,4,5) -DryRun }
        '4' {
                if (-not (Test-Admin)) { Write-Stage "Heads-up: not elevated, stage 4 may fail." "WARN" }
                Invoke-Chain -Stages @(1,2,3,4,5) -PauseBetween
             }
        '5' { Invoke-Chain -Stages @(1,5) -PauseBetween }
        '6' {
                $s = Read-Host "Stage number (1-5)"
                if ($s -match '^[1-5]$') { Invoke-Chain -Stages @([int]$s) -PauseBetween }
                else { Write-Stage "Not a valid stage." "WARN"; Pause-Return }
             }
        '7' { Show-Expected }
        'Q' { break }
        default { }
    }
} while ($true)

Write-Host "`nBye. Open Cortex XSIAM/XDR to review the alerts.`n" -ForegroundColor Green
